### PR TITLE
update travis

### PR DESCRIPTION
**Pull request by cbaker6**
Makes travis work with main branch. Will need to to switch the default branch to main along with the branch protection settings

### CODE REVIEW

**Review by davimacedo — APPROVED** [review]
LGTM

**Comment by davimacedo** [comment]
@cbaker6 Could you please double check if I did the change right?

**Comment by cbaker6** [comment]
@davimacedo yup, everything looks good

**Comment by davimacedo** [comment]
Should we delete the master branch?

**Comment by cbaker6** [comment]
I just deleted it. If we ever need again we can branch from main

**Pull request merged**
